# Generated by Django 4.1.5 on 2023-01-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editblog',
            options={'verbose_name': '笔记', 'verbose_name_plural': '笔记'},
        ),
        migrations.AddField(
            model_name='editblog',
            name='preface',
            field=models.TextField(default='blog_preface'),
            preserve_default=False,
        ),
    ]
