# Generated by Django 4.1.5 on 2023-02-12 07:03

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='preface',
            field=models.TextField(default='add_markdown'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
